version: '3'
services:
  serverless:
    container_name: serverless-chat-ai-api
    build:
      context: ./docker
      args:
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    tty: true
    volumes:
      - ./src:/app
    working_dir: /app
    ports:
      - 3000:3000
    env_file:
      - .env